### PR TITLE
Add message attributes support

### PR DESCRIPTION
**Pull request by hcwilhelm**
- I needed to add support for message attributes to build an RPC system on top of 
SQS streams. 

- Also I updated all library dependency versions as well as sbt, scala and
sbt-plugins.

- I fixed all deprecated warnings for the compile task.

### CODE REVIEW

**Comment by hcwilhelm** [comment]
@s12v do you maybe want to review my PR and than finally merge it or is this project dead.

**Review by s12v — APPROVED** [review]

**Comment by s12v** [comment]
@hcwilhelm, sorry, missed this one. Thanks.

**Comment by hcwilhelm** [comment]
@s12v nice thanks now I can depend on the main project instead of my clone 👍

**Comment by s12v** [comment]
@hcwilhelm, I will release a new version later this week.

**Comment by s12v** [comment]
@hcwilhelm, released 0.2.2

**Comment by hcwilhelm** [comment]
@s12v awesome thank you

**Pull request merged**
